version: 2

project_name: gitdeps

metadata:
  maintainers:
    - "Michael Neonov <two.nelonn at gmail.com>"
  license: "MIT"
  homepage: "https://github.com/Nelonn/gitdeps"
  description: "Git dependencies manager. Simplified version of git submodules."

builds:
  - id: linux
    goos: [linux]
    goarch: ['386', arm, amd64, arm64]
    env: [CGO_ENABLED=0]
    main: ./gitdeps.go
    ldflags:
      - -s -w -X main.Version={{.Version}}

  - id: darwin
    goos: [darwin]
    goarch: [amd64, arm64]
    env: [CGO_ENABLED=0]
    main: ./gitdeps.go
    ldflags:
      - -s -w -X main.Version={{.Version}}

  - id: windows
    goos: [windows]
    goarch: ['386', amd64, arm64]
    env: [CGO_ENABLED=0]
    main: ./gitdeps.go
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - id: linux-archive
    builds: [linux]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    wrap_in_directory: true
    format: tar.gz
    files:
      - LICENSE
  - id: darwin-archive
    builds: [darwin]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    wrap_in_directory: true
    format: zip
    files:
      - LICENSE
  - id: windows-archive
    builds: [windows]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    wrap_in_directory: false
    format: zip
    files:
      - LICENSE

brews:
  - dependencies:
      - git
    repository:
      owner: Nelonn
      name: homebrew-tap
      branch: main
      token: "{{ .Env.REPO_HOMEBREW_TAP_WRITE }}"

nfpms:
  - bindir: /usr/bin
    dependencies:
      - git
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux

nix:
  - dependencies:
      - git
    repository:
      owner: Nelonn
      name: nur-packages
      branch: master
      token: "{{ .Env.REPO_NUR_PACKAGES_WRITE }}"
